name: Build 32-bit static softflowd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: i386/debian:bullseye

    steps:
      - run: |
          apt-get update && \
          apt-get install -y build-essential libpcap-dev autoconf automake libtool git strip

      - run: |
          git clone https://github.com/irino/softflowd.git
          cd softflowd
          autoreconf -i
          ./configure CFLAGS="-static -Dlinux"
          make
          strip softflowd

      - uses: actions/upload-artifact@v4
        with:
          name: softflowd-32bit-static
          path: softflowd/softflowd
