name: Build 32-bit static softflowd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: i386/debian:bullseye

    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential gcc-multilib g++-multilib \
            libpcap-dev autoconf automake libtool git

      - name: Clone and build softflowd
        run: |
          git clone https://github.com/irino/softflowd.git
          cd softflowd
          autoreconf -i
          ./configure CFLAGS="-static -m32"
          make
          strip softflowd
          mkdir -p /artifacts
          cp softflowd /artifacts/

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: softflowd-32bit-static
          path: /artifacts/softflowd
