name: Build static 32-bit softflowd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies for 32-bit cross-build
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib \
              libpcap-dev:i386 autoconf automake libtool git make

      - name: Clone and build softflowd
        run: |
          git clone https://github.com/irino/softflowd.git
          cd softflowd
          autoreconf -i
          ./configure CFLAGS="-m32 -static"
          make
          strip softflowd
          mkdir -p artifacts
          cp softflowd artifacts/softflowd-32bit-static

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: softflowd-32bit-static
          path: artifacts/softflowd-32bit-static
